### ISSUE TITLE
with channel 3.1/stable cluster doesn't form, status is "Errored with 0 known peers" on first unit

### ISSUE THREAD

**Issue by xavpaice** [juju-solutions/layer-etcd#135]
When we deploy with channel=3.1/stable, the 'old' status command etcdctl cluster-health is no longer available.  The status of the first unit then returns `Errored with 0 known peers`, and subsequent units are stuck unable to join the cluster.

If we run `ETCDCTL_API=3 etcdctl member list` on the first unit, the unit does at least show up.

```
root@juju-2b11a1-4-lxd-10:~# ETCDCTL_API=3 etcdctl endpoint health
127.0.0.1:2379 is healthy: successfully committed proposal: took = 541.223µs
root@juju-2b11a1-4-lxd-10:~# ETCDCTL_API=3 etcdctl endpoint status
127.0.0.1:2379, fccde205e2d7f075, 3.1.10, 25 kB, true, 2, 7
```

**Comment by gnuoy** [comment]
I believe this issue is specific to a fork of the layer which disables client tls as a temporary work around for an issue with etcd client fail-over which is tracked in the following bugs:
https://bugs.launchpad.net/vault-charm/+bug/1782620
https://github.com/hashicorp/vault/issues/4961
https://github.com/coreos/etcd/issues/9949

**Comment by gnuoy** [comment]
I think this issue can be closed since the issue is specific to a fork of the charm.

**Comment by xavpaice** [comment]
https://bugs.launchpad.net/vault-charm/+bug/1782620/comments/8 did the trick perfectly - thanks!
